# Generated by Django 5.0.7 on 2024-10-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("location", models.CharField(max_length=100)),
                ("career_summary", models.TextField(blank=True)),
                ("education", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("job_experiences", models.JSONField(default=list)),
                ("projects", models.JSONField(default=list)),
                ("certificates", models.JSONField(default=list)),
            ],
        ),
    ]
