# Generated by Django 5.0.7 on 2024-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_builder", "0002_resumetemplate_remove_resume_certificates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal_infoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "preview_image",
                    models.ImageField(upload_to="Personal_info_templates/"),
                ),
                ("html_template", models.TextField()),
                ("css_template", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Resume",
            new_name="Personal_info",
        ),
        migrations.DeleteModel(
            name="ResumeTemplate",
        ),
        migrations.RenameField(
            model_name="certificate",
            old_name="resume",
            new_name="Personal_info",
        ),
        migrations.RenameField(
            model_name="education",
            old_name="resume",
            new_name="Personal_info",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="resume",
            new_name="Personal_info",
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="resume",
            new_name="Personal_info",
        ),
        migrations.RenameField(
            model_name="workexperience",
            old_name="resume",
            new_name="Personal_info",
        ),
    ]
